Map<String,String>  arabicStrings = {
'home':'الرئيسية' ,
  'offers' : 'العروض',
  'partners':'الشركاء',
  'points_calc':"حساب النقاط",
  'accounts':'العضويات',
  'golden_account':'عضوية ذهبية',
  'pont':'نقطة' ,
  'welcome_to_shara':'مرحباً بك في شارة',
  'show_all':'المزيد',
  'last_operations':"العمليات السابقة",
  "all":"الكل",
  'dont_miss_offers':'لا تفوتك عروض شارة',
  'brand_name':'اسم البراند' ,
  'profile':'حسابي الشخصي' ,
  'profile_info':'المعلومات الشخصية' ,
  'account_setting':'إعدادات الحساب',
  'proce_invoices':'العمليات والفواتير',
  'send_message':'ارسال رسالة' ,
  'sign_in':'تسجيل الدخول'  ,
  'email':'البريد الإلكتروني',
  'verify_id':'وثق هويتك',
  'confirm_verification':'تأكيد التحقق',
  'password':'كلمة المرور',
  'verified':'تم التحقق',
  'id_verification_done':'تم التحقق من هويتك بنجاح',
  "create_password":"إنشاء كلمة المرور",
  'current_password':'كلمة المرور الحالية',
  'change_password':'تغيير كلمة المرور',
  'confirm_password':'تأكيد كلمة المرور',
  'new_password':'كلمة المرور الجديدة',
  'new_confirm_password':'تأكيد كلمة المرور الجديدة',
  'dont_have_account':'ليس لديك حساب في شارة؟',
  'forget_password':'نسيت كلمة المرور؟' ,
  'join_now':'اشترك الآن' ,
  'create_account':'انشاء حساب',
  'create':'إنشاء',
  'press_to_verify_id':'اضغط لتوثيق هويتك',
  'data_record':"سجل البيانات",
  'verify_your_id':'وثق هويتك',
  'full_name':'الاسم الاول',
  'enter_your_name':'ادخل الاسم الاول',
  'last_name':'الاسم الاخير',
  'enter_last_name':'ادخل الاسم الاخير',
  'phone_number':'رقم الهاتف',
  'email_address':'عنوان البريد',
  'date_of_birth':'تاريخ الميلاد',
  'sign_up':'سجل الآن' ,
  'shara_offers':'عروض شارة'   ,
  'filter':'تصفية',
  'change':'تغيير',
  'lang':'English',
  "notifications":"الإشعارات",
  "no_notis_yet":"لا يوجد إشعارات بعد",
  'offer_data':'احصل الان على تخفيضات ٢٥٪ عند الشراء',
  'shop_now':'تسوق الآن',
  'disc_coupon':'العروض',
  'Error':'خطأ',
  'lang_code':'ar',
  'nomore_discount_coupons':'لا يوجد مزيد من كوبونات خصم',
  'copy_coupon':'نسخ الكوبون',
  'change_email':'تغيير البريد الالكتروني',
  'new_email':'البريد الالكتروني الجديد',
  'change_lang':"تغيير اللغة",
  'login_email':'رقم الهاتف',
  'enter_login_email' :'ادخل رقم الهاتف',
  'The email has already been taken.':'البريد الالكلتروني مسجل مسبقا',
  'The phone has already been taken.':'رقم الهاتف مسجل مسبقا',
  'The phone format is invalid.':'رقم الهاتف الذي تم ادخاله غير صحيح',
  'email_must_fill':'يجب ادخال البريد الالكتروني',
  'email_phone_must_fill' :"يجب ادخال رقم الهاتف",
  'password_must_fill':"يجب ادخال كلمة المرور",
  "confirm_password_not_match":"كلمة المرور وتأكيد كلمة المرور غير متطابقتين",
  'confirm_password_empty':"يرجي ادخال تاكيد كلمة المرور",
  'enter_a_valid_email':"يرجي ادخال بريد الكتروني صحيح",
  'password_less_than_6':'كلمة المرور يجب الا تقل عن 8 حروف',
  'name_must_fill':'يجب ادخال الاسم الاول',
  'currentPassword_password_not_match':'كلمة المرور التي تم ادخالها وكلمة المرور الحالية غير متطابقتين',
  'email_current_email_not_match':'البريد الالكتروني الذي تم ادخاله لا يطابق بريدكم الالكتروني',
  'last_name_must_fill':'يجب ادخال الاسم الاخير',
  'phone_must_fill':'يجب ادخال رقم الجوال',
  'enter_valid_phone':'يجب ادخال رقم جوال صحيح',
  'birth_date_must_fill':'يجب اختيار تاريخ الميلاد'  ,
  'account_info':"الملف الشخصي",
  'personal_info_spc':'المعــلومــات الشــخــصــية',
  'member_type':'نوع العضوية',
  'member_id':'رقم العضوية',
  'subscribe_date':'تاريخ الاشتراك',
  'points_count':'عدد النقاط',
  'name':'الإسم',
  'membership_feature':'مميزات العضوية',
  'secret_number':'الرقم السري',
  'phone':'الجوال',
  'birth_date':'تاريخ الميلاد',
  'save_changes':'حفظ التعديلات',
  'send':'إرسال',
  'confirm':'تأكيد',
  'message':'الرسالة',
  'search_account':"البحث عن حسابك" ,
  'forget_password_instruction':'ادخل بريدك الإلكتروني أو رقم الجوال وسوف يتم ارسال رابط لتجديد كلمة المرور',
  'date_filtering':'فرز حسب التاريخ' ,
  'brand_filtering':'فرز حسب الماركة',
  'brand_name_filter':'اسم العلامة التجارية' ,
  'invoice_number':'رقم الفاتورة',
  'mark_name':'اسم الماركة',
  'process_value':'قيمة المعاملة',
  'earning_points':'النقاط المكتسبة',
  'spending_points':'النقاط المستهلكة',
  'date':'التاريخ' ,
  'calculate_page_header_text':'احسب عدد النقاط التي يمكنك كسبها وإنفاقها من كل ماركة' ,
  'earn_shara_points':'كسب نقاط شارة',
  'spend_shara_points':'انفاق نقاط شارة',
  'how_much_to_save':'كم يمكنك توفيره مع شارة',
  'select_membership_type':'اختار نوع العضوية',
  'enter_points_number':'ادخل عدد النقاط',
  'number_of_points':'عدد النقاط',
  'SR':'ريال' ,
  'Point':'نقطة' ,
  "finance":"الحسابات",
  "value":"قيمة الكوبون",
  "show_coupon":"اطلع على الكوبون",
  'user_full_name':'الاسم',
  'log_out':'تسجيل الخروج',
  'reset_password':'إعادة تعيين كلمة المرور',
  "email_not_found":"البريد الالكتروني غير مرتبط بحساب على شارة",
  "phone_not_found":"هذا الجوال غير مرتبط بحساب على شارة",
  'there_is_wrong_somewhere':'هناك خطأ ما، حاول مرة اخرى',
  'select_brand':'اختر العلامة التجارية',
  'number_of_points_will_earn':'عدد النقاط التي ستحصل عليها' ,
  "current_balance":"الرصيد الحالي",
  'how_much_you_will_spend_in_sr':'كم المبلغ الذي تريد إنفاقه أدخل المبلغ الـ ر.س',
  'sum_will_be_spend':'المبلغ المراد إنفاقه',
  'shara_membership':'عضويات شارة' ,
  'read_more':'اقرأ المزيد',
  'golden_member':'العضوية الذهبية',
  'code':'الكود',
  'no_coupons_yet':"لم تقم بشراء اي قسيمة شراء بعد",
  'Enter_code_error_message':'يرجي إدخال الكود',
  'enter_emailed_code':'ادخل الكود الذي تم ارساله الي بريدك الالكتروني',
  'enter_code'    :'ادخل الكود',
  'silver_membership':  'العضوية الفضية' ,
  'copper_membership': 'العضوية البرونزية',
  'invalid_code_entered':'الكود الذي تم ادخاله غير صالح' ,
  'this_field_must_fill':'يجب ملأ هذا الحقل',
  'merchant_order_id' :'رقم طلب المتجر',
  'offer_online_at_shop':'العرض ساري اون لاين وبالفروع',
  'transaction_status_completed': 'عملية مكتملة',
  'transaction_status_not_completed': 'عملية غير مكتملة',
  'transaction_status':'الحالة',
  'sum_in_sr':'المبلغ بالريال',
  'enter_sum_in_sr':'ادخل المبلغ بالريال' ,
  "replace_points":"استبدال النقاط" ,
  "add_to_cart":'أضف للسة' ,
  "points_calculator":"حاسبة النقاط" ,
  "points_calculator_description":"احسب عدد نقاط شارة التي يمكنك كسبها وإنفاقها"  ,
  "coupons":"قسائم الشراء",
  "buy":"شراء",
  "more":"المزيد",
  "continue":"انشاء حساب الأن",
  "verification":"التوثيق",
  "clear_all":"مسح",
  "verify":"تحقق",
  "did_get_code?":"ألم تتلق رمزاً؟",
  "resent_again":"إعادة إرسال",
  "enter_code_from_mobile":"ادخل الكود المرسل على الجوال",
  "replacement_fee":"تكلفة الاستبدال",
  "start_price":"السعر يبدأ من :",
  "price":"السعر",
  "not_available":"غير متاح",
  "Close":"إغلاق",
  'your_points':'نقاطك',
  "code_will_be_received":"سيصلك رمز التحقق",
  "buying_success":"تم الشراء بنجاح",
  "no_items_in_category":"لا توجد عناصر في هذه المجموعة",
  "my_coupons":"قسائم الشراء الخاصة بي",
  "points_to_cash":"نقاطك حولها لكاش",
  "points_to_sells":"استبدل نقاطك بمشتريات",
  "points_for_u_beloveds":"نقاطك لك ولأحبابك",
  "next":"التالي",
  "start":"ابدأ",
  "skip":"تخطي",

  'transfer_points':'تحويل نقاط',
  'add_balance':'إضافة رصيد',
  'international_transfer':'تحويل دولي',
  'local_transfer':'تحويل محلي',
'balance':'رصيد',
'my_account':'حسابي',
  'please_points_to_buy':'من فضلك ادخل عدد النقاط المراد شراؤها',
  'insert_points_to_buy':'أدخل عدد النقاط المراد شراءها',
  'not_me':'الدخول بحساب اخر او انشاء كلمة مرور جديدة',
'invite':'دعوة',
  'points_to_transfer':'النقاط المراد تحويلها',
  'something_went_wrong':'هناك خطأ ما، يرجي المحاولة في وقت لاحق',

  'enter_contact_phone':'ادخل رقم الجوال',
  'enter_valid_amount':'ادخل قيمة التحويل',

  'phone_or_password_uncorrect':'ليس لديك حساب في شارة',
  'wrong_password':'كلمة المرور غير صحيحة',
  'code_not_correct_expired':'كود التفعيل غير صحيح او انتهت صلاحيته',

  'by_presseing_continue':'بالضغط على استمرار انت توافق على',
  'terms_and_conditions':'الشروط والأحكام',
  'and':'و',
  'privacy_policy':'سياسة الخصوصية',

  'choose_money_add_method':'اختار طريقة تحويل الأموال',
  'local_transfer_page':'حوالة محلية',
  'S.R':'ر.س',
'search_by_name':'البحث بالاسم',
  'transfer_to':'التحويل الى',
'enter_beneficiary_name':'ادخل اسم المستفيد',
  'sum_to_transfer':'مبلغ التحويل',
  'iban':'الأيبان',
  'iban_desc':'الرقم المصرفي',
  'show_last_operations':'عرض كل العمليات السابقة',
  'the_reason':'السبب',
  'reason_porpose':'الغرض من التحويل',
  'add_info':'إضافة معلومات',
  'notice':'ملاحظة',
  'ensure_the_correct_iban_name_with_bank':'يرجي التأكد من صحة الاسم والأيبان مع بنك المستفيد',
  'conform':'تأكيد',

  'end_with':'المنتهي بـ',
  'ex_transfers':'التحويلات السابقة',
  'transfer_to_new':'التحويل لمستفيد جديد',
  'choose_beneficiaries':'اختر المستفيد الذي تريد التحويل إليه',
  'beneficiaries':'المستفيدين',

  'inesta_add':'الايداع الفوري',
  'bank_transfer_to':'التحويل البنكي إلى',
  'credit_card':'البطاقة الإئتمانية',

  'enter_conf_code_correctly':'يرجي إدخال كود التفعيل بشكل صحيح',

  'registered_number_login':'هذا الرقم مسجل من قبل. يمكنك تسجيل الدخول',

  'transfer_to_contact':'التحويل الى جهة اتصال',
  'contact':'جهة اتصال',
  'contacts':'جهات الاتصال',
  'transfer_to_unregistered':'التحويل لرقم غير مسجل',

  "shara_description":"برنامج ولاء فاخر تم تصميمه بعناية يمنحك عالما من المزايا الحصرية التي تخولك لاكتساب نقاط واستبدالها لتتمتع بالعديد من الخدمات",
  "points_to_cash_description":"يمكنك جمع نقاطا أكثر وتحويلها إلى كاش ينزل لك على حسابك البنكي",
  "points_to_sells_description":"تسوقك صار امتع، استبدل نقاطك مع شارة بالعديد من المشتريات لدى أكثر من ٤ آلاف علامة تجارية محلية وعالمية",
  "points_for_u_beloveds_description":"فاجيء أهلك وأصدقائك وأسعدهم بهدايا عبارة عن رصيد نقاط عبر التحويل من رصيدك إلى رصيدهم",
} ;