Map<String, String> englishString = {
  'home': 'Home',
  'offers': 'Offers',
  'partners': 'Partners',
  'points_calc': "Calculate Points",
  'accounts': 'Memberships',
  'golden_account': 'Golden membership',
  'pont': 'Point',
  'welcome_to_shara': 'Welcome to Shara',
  'show_all': 'More',
  'last_operations': "Last operations",
  'dont_miss_offers': "Don't miss shara offers",
  'brand_name': 'Brand name',
  'profile': 'Profile',
  'wrong_password': 'Wrong password',
  'profile_info': 'Personal information',
  'account_setting': 'Account settings',
  'proce_invoices': 'Transactions and invoices',
  'send_message': 'Send message',
  'sign_in': 'Sign in',
  'email': 'Email',
  'user_full_name': 'Name',
  'password': 'Password',
  'verify_id': 'Verify your ID',
  'verified': 'Verified',
  'current_password': 'Current password',
  'id_verification_done': 'ID verification done successfully',
  'change_password': 'Change password',
  'press_to_verify_id': 'Press to verify your ID',
  'verify_your_id': 'Verify your ID',
  'confirm_verification': 'Confirm Verification',
  'confirm_password': 'Confirm password',
  'new_password': 'New password',
  'new_confirm_password': 'Confirm new password',
  'dont_have_account': "Don't have account on shara?",
  'forget_password': 'Forget password?',
  'join_now': 'Join now',
  "notifications": "Notification",
  "no_notis_yet": "There are no notifications yet",
  "all": "All",
  'create_account': 'Create account',
  'data_record': "Data record",
  'full_name': 'First name',
  'enter_your_name': 'Enter first name',
  'last_name': 'Last name',
  'enter_last_name': 'Enter last name',
  'phone_number': 'Phone number',
  'email_address': 'Email address',
  'date_of_birth': 'Date of birth',
  'sign_up': 'Sign up now',
  'shara_offers': 'Shara Offers',
  'filter': 'Filter',
  'change': 'Change',
  'offer_data': 'Get 25% off when buying',
  'shop_now': 'Shope now',
  'Error': 'Error',
  'disc_coupon': 'Offers',
  'lang_code': 'en',
  'change_email': 'Change email',
  'new_email': 'New email',
  'change_lang': "Change language",
  'copy_coupon': 'Copy coupon',
  'login_email': 'phone number',
  'lang': 'عربي',
  'nomore_discount_coupons': 'No more discount coupons',
  'enter_login_email': 'Enter phone number',
  'The email has already been taken.': 'This email has already been taken',
  'The phone has already been taken.': 'The phone has already been taken.',
  'The phone format is invalid.': 'The phone format is invalid.',
  'email_must_fill': 'Please enter email',
  'email_phone_must_fill': "Please enter phone number",
  'password_must_fill': "Please enter password",
  "confirm_password_not_match": "Password and confirm password does not match",
  'confirm_password_empty': "Please enter confirm password",
  'enter_a_valid_email': "Please enter a valid email",
  'password_less_than_6': 'Password must not be less than 8 characters',
  'name_must_fill': 'Please enter first name',
  'currentPassword_password_not_match':
      'Password and current password does not match',
  'email_current_email_not_match': 'The email does not match your email',
  'last_name_must_fill': 'Please enter last name',
  'phone_must_fill': 'Please enter phone number',
  'enter_valid_phone': 'Please enter a valid phone number',
  'birth_date_must_fill': 'Please enter birth date',
  'account_info': "Account information",
  'personal_info_spc': 'Personal information',
  'member_type': 'Membership type',
  'member_id': 'Membership number',
  'subscribe_date': 'Subscribe date',
  'points_count': 'Points number',
  'name': 'Name',
  'membership_feature': 'Membership feature',
  'secret_number': 'Secret number',
  'phone': 'Phone',
  'birth_date': 'Date of birth',
  'save_changes': 'Save changes',
  'send': 'Send',
  'message': 'Message',
  'search_account': "Search for account",
  'forget_password_instruction':
      'Enter your email or phone number and we will send link to reset your password',
  'date_filtering': 'Filter by date',
  'brand_filtering': 'Filter by brand',
  'brand_name_filter': 'Brand name',
  'invoice_number': 'Invoice number',
  'mark_name': 'Brand name',
  'process_value': 'Transaction value',
  'earning_points': 'Earned points',
  'date': 'Date',
  'spending_points': 'Spending points',
  'calculate_page_header_text':
      'Calculate points that can be earned and spent for every brand',
  'earn_shara_points': 'Earn shara points',
  'spend_shara_points': 'Spend shara points',
  'how_much_to_save': 'Saved amount with shara',
  'select_membership_type': 'Select membership type',
  'enter_points_number': 'Enter number of points',
  'number_of_points': 'Points number',
  'SR': 'SR',
  'Point': 'Point',
  'log_out': 'Log out',
  "show_coupon": "Show coupon",
  'reset_password': 'Reset password',
  "email_not_found": "This email is not on shara",
  "phone_not_found": "This phone number is not on shara",
  'there_is_wrong_somewhere': 'There is something wrong,try again',
  'select_brand': 'Select a brand',
  'number_of_points_will_earn': 'Points you will earn',
  'how_much_you_will_spend_in_sr': 'How much you will spend in SR?',
  'sum_will_be_spend': 'Amount will be spend',
  'shara_membership': 'Shara membership',
  'read_more': 'Read more',
  'golden_member': 'Golden membership',
  'code': 'Code',
  "value": "Coupon Value",
  "replacement_fee": "Replace with",
  "finance": "Finance",
  'no_coupons_yet': "You have not bought any coupon yet",
  'Enter_code_error_message': 'Please enter the code',
  'enter_emailed_code': 'Enter the code that was sent to your email',
  'enter_code': 'Enter the code',
  'silver_membership': 'Silver membership',
  'copper_membership': 'Bronze membership',
  'invalid_code_entered': 'Invalid code',
  'this_field_must_fill': 'This field must be filled',
  'merchant_order_id': 'Merchant Order Id',
  'offer_online_at_shop': 'This offer is online and shop',
  'transaction_status_completed': 'Transaction completed',
  'transaction_status_not_completed': 'Transaction not completed',
  'transaction_status': 'Status',
  'sum_in_sr': 'Sum in SR',
  'enter_sum_in_sr': 'Enter sum in SR',
  'replace_points': 'Replace Points',
  "add_to_cart": "Add to cart",
  "points_calculator": "Points Calculator",
  "points_calculator_description":
      "Calculate Shara points that you can earn and spend",
  "coupons": "Coupons",
  "buy": "Buy",
  "more": "More",
  "next": "Next",
  "start": "Start",
  "skip": "Skip",
  "start_price": "Price Start from",
  "price": "Price",
  "code_will_be_received": "Verification code will be received",
  "not_available": "Not available",
  "buying_success": "Buying successfully",
  "no_items_in_category": "No items in this category",
  "my_coupons": "My coupons",
  "points_to_cash": "Convert your points to cash",
  "continue": "Create account",
  "create_password": "Create password",
  "verification": "Verification",
  "clear_all": "Clear",
  "verify": "Verify",
  'create': 'Create',
  'confirm': 'Conform',
  'your_points': 'Your points',
  'balance': 'Balance',
  'S.R': 'SR',
  'not_me': 'Login with another account or create new password',
  'something_went_wrong': 'Something went wrong, try again later',
  'phone_or_password_uncorrect': 'You do not have account on shara',
  'transfer_to': 'Transfer to',
  'enter_beneficiary_name': 'Enter beneficiary name',
  'sum_to_transfer': 'The sum',
  'iban': 'IBAN',
  'my_account':'My account',
  'iban_desc': 'IBAN',
  'the_reason': 'The reason',
  'invite':'Invite',
  'by_presseing_continue':'by pressing continue you agree on',
  'terms_and_conditions':'Terme and conditions',
  'and':'and',
  'privacy_policy':'Privacy policy',

  'reason_porpose': 'A reason to transfer',
  'add_info': 'Add information',
  'notice': 'Notice',
  'ensure_the_correct_iban_name_with_bank':
      'Please, ensure the correct name and IBAN',
  'conform': 'Conform',
  'show_last_operations':'Show all last operations',
  'search_by_name': 'Search by name',
  'transfer_to_contact': 'Transfer to contact',
  'contact': 'Contact',
  'contacts': 'Contacts',
  'end_with': 'Ends with ',
  'transfer_to_unregistered': 'Transfer to unregistered number',
  'ex_transfers': 'Previous transfers',
  'transfer_to_new': 'Transfer to new beneficiary',
  'choose_beneficiaries': 'Choose the beneficiary that you want to transfer to',
  'beneficiaries': 'Beneficiaries',
  'transfer_points': 'Transfer points',
  'add_balance': 'Add balance',
  'international_transfer': 'International transfer',
  'local_transfer': 'Local transfer',
  'local_transfer_page': 'Local transfer',
  'choose_money_add_method': 'Choose adding money method',
  'inesta_add': 'Instant deposit',
  'bank_transfer_to': 'Bank transfer to',
  'credit_card': 'Credit card',
  'registered_number_login': 'This number is already registered. You can Login',
  'enter_conf_code_correctly': 'Enter confirmation code correctly',
  "current_balance": "Current balance",
  "did_get_code?": "Didn't receive code?",
  "resent_again": "Resent again",
  "enter_code_from_mobile": "Enter a code that has been sent to your mobile",
  "points_to_sells": "Redeem your points for purchases",
  "points_for_u_beloveds": "Your points for you and beloveds",
  "shara_description":
      "A luxurious loyalty program that has been carefully designed to give you a world of exclusive benefits that enable you to earn points and redeem them to enjoy many services.",
  "points_to_cash_description":
      "You can collect more points and convert them into cash that will be sent to you on your bank account",
  "points_to_sells_description":
      "Your shopping has become more enjoyable, redeem your points with a badge for many purchases at more than 4,000 local and international brands.",
  "points_for_u_beloveds_description":
      "Surprise your family and friends and make them happy with gifts that are points balance by transferring from your balance to their balance",
};
